# Generated by Django 3.2.9 on 2021-12-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50, unique=True)),
                ('website', models.URLField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Not active')], default=0)),
            ],
            options={
                'ordering': ['provider_name'],
            },
        ),
    ]
