# Generated by Django 3.2.9 on 2021-12-15 14:39

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=15)),
                ('member_number', models.CharField(blank=True, max_length=15)),
                ('pension_type', models.IntegerField(choices=[(0, 'Occupational Pension Scheme'), (1, 'PRSA'), (2, 'RAC / Personal Pension'), (3, 'Retirement Bond')], default=0)),
                ('date_joined_scheme', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pao', models.BooleanField(default=False)),
                ('director', models.BooleanField(default=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensions', to=settings.AUTH_USER_MODEL)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_pensions', to='jobs.job')),
                ('pension_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_pensions', to='pensions.provider')),
            ],
            options={
                'ordering': ['-date_joined_scheme'],
            },
        ),
    ]
